const mongoose = require('mongoose');

const SubCategorySchema = new mongoose.Schema({
  category_Id: {
    type: mongoose.Schema.ObjectId,
    ref: 'Category'
  },
  title: {
    type: String,
    required: [true, 'Please enter a sub-category'],
    enum: [
      'Groceries',
      'Restaurants',
      'Personal Supplies',
      'Clothes',
      'Laundry/detergents',
      'Hair/beauty',
      'Subscriptions',
      'Other',
      'Tuition',
      'Books',
      'Music lessons',
      'Concerts/shows',
      'Games',
      'Hobbies',
      'Movies',
      'Music',
      'Outdoor activities',
      'Photography',
      'Sports',
      'Theater/plays',
      'TV',
      'Activities',
      'School',
      'Books, crafts, games',
      'Toys',
      'Gifts',
      'Donations (charity)',
      'Car',
      'Health',
      'Doctors/dental/vision',
      'Specialty care',
      'Pharmacy',
      'Supplements',
      'Emergency',
      'Phone',
      'Rent',
      'Internet',
      'Electricity',
      'Heat/gas',
      'Water',
      'Trash',
      'Furnishings',
      'Lawn/garden/plants',
      'Supplies (cleaning etc)',
      'Maintenance',
      'Improvements',
      'Domains & hosting',
      'Online services',
      'Hardware',
      'Software',
      'Gadgets',
      'Electronic equipment',
      'Fuel',
      'Car payments',
      'TAXI',
      'Registration/license',
      'Supplies',
      'Public transit'
    ]
  }
});

module.exports = mongoose.model('Subcategory', SubCategorySchema);
